repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1-1
    hooks:
      - id: autopep8-wrapper
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
      - id: pyupgrade
